# Generate hmm_spy.c — full x86 forwarding spy for hmm.dll.
# Compile: python -m ziglang cc -target x86-windows-gnu -shared -O2 -o hmm.dll hmm_spy.c hmm_spy.def
#
# v25.5 spy fixes (session I, 2026-09-26):
#   1. ALL exports are stdcall(4 ints) with DECORATED names — the AX binds
#      every hmm call as _NAME@16 with 4 int pushes (see start_ax_dump.hsp
#      #func lines), so bare (void) exports never resolve: the game dies
#      with HSP #Error 38 on the first DGCLEAR.
#   2. hmm_spy.def pins the export names: zig/LLVM strips the leading
#      underscore on @16 exports (DGCLEAR@16 instead of _DGCLEAR@16); the
#      .def maps _NAME@16 = NAME@16 so all 114 decorated names survive.
#   3. Flushes per [pc-dump] FLUSH on DGGCOPY 5 (POV composite) as before.
# Session-I evidence collected with a temporary vertex-ring probe build:
#   the real FUN_10002550 centers flag&1 prims by the DEST size
#   (x0 = pos - dest_w/2, +0.5 D3D half-pixel) — captured as
#   [pc-q] rect=(0,101 34x2) pos=17 raw=32 -> L=1.5 R=33.5.
import os

CUSTOM = {
    "DGCOLOR":      '[pc] logf("[pc-maw] DGCOLOR %d %d %d %d", a0,a1,a2,a3)',
    "DGGSEL":       '[pc] logf("[pc-maw] DGGSEL %d", a0)',
    "DGCLEAR":      '[pc] logf("[pc-maw] DGCLEAR")',
    "DGRECT":       '[pc] logf("[pc-maw] DGRECT %d %d %d %d", a0,a1,a2,a3)',
    "DGPOS":        '[pc] logf("[pc-maw] DGPOS %d %d", a0,a1)',
    "DGSCALEANDANGLE": '[pc] logf("[pc-maw] DGSCALEANDANGLE %d %d %d sc=(%.2f,%.2f)", a0,a1,a2,a0/256.0,a1/256.0)',
    "DGBLENDMODE":  '[pc] logf("[pc-maw] DGBLENDMODE %d", a0)',
    "DGGCOPY":      '[pc] logf("[pc-maw] DGGCOPY id=%d flags=0x%x", a0,a1)',
    "DGTEXTURE":    '[pc] logf("[pc-maw] DGTEXTURE %d", a0)',
    "DGADDPRIMITIVE": '[pc] logf("[pc-prim] DGADDPRIMITIVE flags=0x%x", a0)',
    "DGDRAWPRIMITIVE": '[pc] logf("[pc-prim] DGDRAWPRIMITIVE")',
    "DGCREATEPRIMITIVE": '[pc] logf("[pc-prim] DGCREATEPRIMITIVE %d", a0)',
    "DGBUFFER":     '[pc] logf("[pc] DGBUFFER id=%d %dx%d", a0,a1,a2)',
    "DGREDRAW":     '[pc] logf("[pc] DGREDRAW")',
    "DGLINE":       '[pc] logf("[pc-maw] DGLINE %d %d -> %d %d", a0,a1,a2,a3)',
}

names = [l.strip() for l in open("hmm_names.txt") if l.strip().endswith("@16")]
plain = [n for n in names if n[1:-3] not in CUSTOM]
custom = [n for n in names if n[1:-3] in CUSTOM]
assert len(plain) + len(custom) == len(names), (len(plain), len(custom), len(names))

out = []
w = out.append
w("/* hmm_spy.c - auto-generated by gen_spy_c.py; do not edit by hand.")
w(" * Forwarding spy for the real hmm.dll (renamed hmm_real.dll).")
w(" * Logs the DG* draw stream; ring-flushes on DGGCOPY 5 (POV composite). */")
w('#include <windows.h>')
w('#include <stdio.h>')
w("")
w("/* ---- ring logger ---- */")
w("#define RINGSZ (4*1024*1024)")
w("static char  g_ring[RINGSZ];")
w("static size_t g_len = 0;")
w("static CRITICAL_SECTION g_cs;")
w("static HANDLE g_file = NULL;")
w("static unsigned g_ep = 0;")
w("static unsigned long long g_tick = 0;")
w("")
w("static void ring_put(const char *s, size_t n) {")
w("    if (g_len + n > RINGSZ) return;")
w("    memcpy(g_ring + g_len, s, n); g_len += n;")
w("}")
w("")
w("static void logf(const char *fmt, ...) {")
w("    char buf[512]; va_list ap; int n;")
w("    va_start(ap, fmt);")
w("    n = _vsnprintf(buf, sizeof(buf)-2, fmt, ap);")
w("    va_end(ap);")
w("    if (n <= 0) return;")
w("    buf[n] = '\\r'; buf[n+1] = '\\n';")
w("    EnterCriticalSection(&g_cs);")
w("    g_tick++;")
w("    ring_put(buf, (size_t)n + 2);")
w("    LeaveCriticalSection(&g_cs);")
w("}")
w("")
w("static void flush_ring(void) {")
w("    DWORD wr;")
w("    if (!g_file || !g_len) return;")
w("    EnterCriticalSection(&g_cs);")
w("    SetFilePointer(g_file, 0, NULL, FILE_END);")
w("    WriteFile(g_file, g_ring, (DWORD)g_len, &wr, NULL);")
w("    g_len = 0;")
w("    LeaveCriticalSection(&g_cs);")
w("}")
w("")
w("static HMODULE g_real = NULL;")
w("")
w("static void *realfn(const char *name) {")
w("    return (void *)GetProcAddress(g_real, name);")
w("}")
w("")
w("BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID r) {")
w("    (void)h; (void)r;")
w("    if (reason == DLL_PROCESS_ATTACH) {")
w("        InitializeCriticalSection(&g_cs);")
w('        g_file = CreateFileA("hmm_spy.log", FILE_APPEND_DATA, FILE_SHARE_READ|FILE_SHARE_WRITE,')
w("                 NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);")
w('        g_real = LoadLibraryA("hmm_real.dll");')
w("        if (!g_real) {")
w('            MessageBoxA(NULL, "hmm_spy: cannot load hmm_real.dll - rename the original hmm.dll to hmm_real.dll", "hmm_spy", MB_ICONERROR);')
w("            return FALSE;")
w("        }")
w('        logf("[pc] hmm_spy attached real=%p", (void*)g_real);')
w("    } else if (reason == DLL_PROCESS_DETACH) {")
w("        flush_ring();")
w("        if (g_file) CloseHandle(g_file);")
w("    }")
w("    return TRUE;")
w("}")
w("")
w("/* ---- logged custom handlers ---- */")
for n in custom:
    base = n[1:-3]
    logline = CUSTOM[base]
    logline = logline[len("[pc] "):]
    # HSP always binds ALL hmm exports as _NAME@16 with 4 pushed args
    # (even DGCLEAR/DGDRAWPRIMITIVE/DGREDRAW: the AX #func lines say
    # "int,int,int,int"), so every spy export must be stdcall(4 ints) with
    # the decorated export name -- a bare (void) export would never resolve
    # and the game dies with #Error 38 on the first DGCLEAR.
    w("__declspec(dllexport) void __stdcall %s(int a0, int a1, int a2, int a3) {" % base)
    if base == "DGGCOPY":
        w("    %s;" % logline)
        w("    if (a0 == 5) {")
        w("        g_ep++;")
        w('        logf("[pc-dump] FLUSH ep=%u t=%llu", g_ep, g_tick);')
        w("        flush_ring();")
        w("    }")
    else:
        w("    %s;" % logline)
    w("    typedef void (__stdcall *F4)(int,int,int,int);")
    w('    F4 f = (F4)realfn("%s");' % n)
    w("    if (f) f(a0, a1, a2, a3);")
    w("}")
w("")
w("/* ---- plain forwarders ---- */")
for n in plain:
    base = n[1:-3]
    w("__declspec(dllexport) void __stdcall %s(int a0, int a1, int a2, int a3) {" % base)
    w("    typedef void (__stdcall *F4)(int,int,int,int);")
    w('    F4 f = (F4)realfn("%s");' % n)
    w("    if (f) f(a0, a1, a2, a3);")
    w("}")
w("")

open(os.path.join(os.path.dirname(__file__), "hmm_spy.c"), "w").write("\n".join(out))
print("generated hmm_spy.c: %d custom + %d plain = %d exports" % (len(custom), len(plain), len(names)))
