/* hmm_spy.c - auto-generated by gen_spy_c.py; do not edit by hand.
 * Forwarding spy for the real hmm.dll (renamed hmm_real.dll).
 * Logs the DG* draw stream; ring-flushes on DGGCOPY 5 (POV composite). */
#include <windows.h>
#include <stdio.h>

/* ---- ring logger ---- */
#define RINGSZ (4*1024*1024)
static char  g_ring[RINGSZ];
static size_t g_len = 0;
static CRITICAL_SECTION g_cs;
static HANDLE g_file = NULL;
static unsigned g_ep = 0;
static unsigned long long g_tick = 0;

static void ring_put(const char *s, size_t n) {
    if (g_len + n > RINGSZ) return;
    memcpy(g_ring + g_len, s, n); g_len += n;
}

static void logf(const char *fmt, ...) {
    char buf[512]; va_list ap; int n;
    va_start(ap, fmt);
    n = _vsnprintf(buf, sizeof(buf)-2, fmt, ap);
    va_end(ap);
    if (n <= 0) return;
    buf[n] = '\r'; buf[n+1] = '\n';
    EnterCriticalSection(&g_cs);
    g_tick++;
    ring_put(buf, (size_t)n + 2);
    LeaveCriticalSection(&g_cs);
}

static void flush_ring(void) {
    DWORD wr;
    if (!g_file || !g_len) return;
    EnterCriticalSection(&g_cs);
    SetFilePointer(g_file, 0, NULL, FILE_END);
    WriteFile(g_file, g_ring, (DWORD)g_len, &wr, NULL);
    g_len = 0;
    LeaveCriticalSection(&g_cs);
}

static HMODULE g_real = NULL;

static void *realfn(const char *name) {
    return (void *)GetProcAddress(g_real, name);
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID r) {
    (void)h; (void)r;
    if (reason == DLL_PROCESS_ATTACH) {
        InitializeCriticalSection(&g_cs);
        g_file = CreateFileA("hmm_spy.log", FILE_APPEND_DATA, FILE_SHARE_READ|FILE_SHARE_WRITE,
                 NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
        g_real = LoadLibraryA("hmm_real.dll");
        if (!g_real) {
            MessageBoxA(NULL, "hmm_spy: cannot load hmm_real.dll - rename the original hmm.dll to hmm_real.dll", "hmm_spy", MB_ICONERROR);
            return FALSE;
        }
        logf("[pc] hmm_spy attached real=%p", (void*)g_real);
    } else if (reason == DLL_PROCESS_DETACH) {
        flush_ring();
        if (g_file) CloseHandle(g_file);
    }
    return TRUE;
}

/* ---- logged custom handlers ---- */
__declspec(dllexport) void __stdcall DGADDPRIMITIVE(int a0, int a1, int a2, int a3) {
    logf("[pc-prim] DGADDPRIMITIVE flags=0x%x", a0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGADDPRIMITIVE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGBLENDMODE(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGBLENDMODE %d", a0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGBLENDMODE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGBUFFER(int a0, int a1, int a2, int a3) {
    logf("[pc] DGBUFFER id=%d %dx%d", a0,a1,a2);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGBUFFER@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGCLEAR(void) {
    logf("[pc-maw] DGCLEAR");
    typedef void (__stdcall *F0)(void);
    F0 f = (F0)realfn("_DGCLEAR@16");
    if (f) f();
}
__declspec(dllexport) void __stdcall DGCOLOR(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGCOLOR %d %d %d %d", a0,a1,a2,a3);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGCOLOR@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGCREATEPRIMITIVE(int a0, int a1, int a2, int a3) {
    logf("[pc-prim] DGCREATEPRIMITIVE %d", a0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGCREATEPRIMITIVE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGDRAWPRIMITIVE(void) {
    logf("[pc-prim] DGDRAWPRIMITIVE");
    typedef void (__stdcall *F0)(void);
    F0 f = (F0)realfn("_DGDRAWPRIMITIVE@16");
    if (f) f();
}
__declspec(dllexport) void __stdcall DGGCOPY(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGGCOPY id=%d flags=0x%x", a0,a1);
    if (a0 == 5) {
        g_ep++;
        logf("[pc-dump] FLUSH ep=%u t=%llu", g_ep, g_tick);
        flush_ring();
    }
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGGSEL(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGGSEL %d", a0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGGSEL@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGLINE(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGLINE %d %d -> %d %d", a0,a1,a2,a3);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGLINE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGPOS(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGPOS %d %d", a0,a1);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGPOS@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGRECT(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGRECT %d %d %d %d", a0,a1,a2,a3);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGRECT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGREDRAW(void) {
    logf("[pc] DGREDRAW");
    typedef void (__stdcall *F0)(void);
    F0 f = (F0)realfn("_DGREDRAW@16");
    if (f) f();
}
__declspec(dllexport) void __stdcall DGSCALEANDANGLE(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGSCALEANDANGLE %d %d %d sc=(%.2f,%.2f)", a0,a1,a2,a0/256.0,a1/256.0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGSCALEANDANGLE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGTEXTURE(int a0, int a1, int a2, int a3) {
    logf("[pc-maw] DGTEXTURE %d", a0);
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGTEXTURE@16");
    if (f) f(a0, a1, a2, a3);
}

/* ---- plain forwarders ---- */
__declspec(dllexport) void __stdcall CHECKPLAY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_CHECKPLAY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDADDGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDADDGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDADDGCOPYALL(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDADDGCOPYALL@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDBGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDBGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDBLENDGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDBLENDGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDBOXF(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDBOXF@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDBUFFER(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDBUFFER@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDCOLOR(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDCOLOR@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDDRAWTEXT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDDRAWTEXT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDGCOPY2(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDGCOPY2@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDGSEL(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDGSEL@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDGZOOM(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDGZOOM@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDLOADMEMORY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDLOADMEMORY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDPAINTGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDPAINTGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDPOS(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDPOS@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDPRINT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDPRINT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDREDRAW(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDREDRAW@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDREVERSE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDREVERSE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDROTATEGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDROTATEGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDSCREEN(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDSCREEN@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDSETRECT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDSETRECT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDSETRENEWALTIMING(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDSETRENEWALTIMING@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DDSUBGCOPY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DDSUBGCOPY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGBMPSAVE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGBMPSAVE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGDRAWTEXT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGDRAWTEXT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGFONT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGFONT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGLOADMEMORY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGLOADMEMORY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGRENEWALTIMING(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGRENEWALTIMING@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DGSCREEN(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DGSCREEN@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETJOYNUM(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETJOYNUM@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETJOYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETJOYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETKEEPJOYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETKEEPJOYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETKEEPKEYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETKEEPKEYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETKEYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETKEYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETMOMENTJOYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETMOMENTJOYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETMOMENTKEYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETMOMENTKEYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETPASTJOYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETPASTJOYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIGETPASTKEYSTATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIGETPASTKEYSTATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DIPLAYEFFECT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DIPLAYEFFECT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DISTICK(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DISTICK@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DISTOPEFFECT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DISTOPEFFECT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMLOADMEMORY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMLOADMEMORY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMPLAY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMPLAY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DMSTOP(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DMSTOP@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSDUPLICATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSDUPLICATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSGETMASTERVOLUME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSGETMASTERVOLUME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSGETVOLUME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSGETVOLUME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHCHECKPLAY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHCHECKPLAY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHGETORIGINALVIDEOSIZE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHGETORIGINALVIDEOSIZE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHGETPLAYPOSITION(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHGETPLAYPOSITION@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHPAUSE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHPAUSE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHPLAY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHPLAY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETFULLSCREEN(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETFULLSCREEN@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETMOVIETODGBUFFER(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETMOVIETODGBUFFER@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETRATE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETRATE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETSEEK(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETSEEK@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETVIDEOPARAM(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETVIDEOPARAM@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETVIDEOVISIBLE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETVIDEOVISIBLE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSETVOLUME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSETVOLUME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSHSTOP(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSHSTOP@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSLOADFNAME2(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSLOADFNAME2@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSLOADMEMORY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSLOADMEMORY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSOGGLOADFNAME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSOGGLOADFNAME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSOGGLOADFNAMETHREAD(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSOGGLOADFNAMETHREAD@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSOGGLOADINGCHECK(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSOGGLOADINGCHECK@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSPLAY(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSPLAY@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSRELEASE(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSRELEASE@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSSETMASTERFORMAT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSSETMASTERFORMAT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSSETMASTERVOLUME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSSETMASTERVOLUME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSSETVOLUME(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSSETVOLUME@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall DSSTOP(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_DSSTOP@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMBITCHECK(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMBITCHECK@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMBITOFF(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMBITOFF@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMBITON(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMBITON@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMEND(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMEND@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMGETFPS(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMGETFPS@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMGETSIN(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMGETSIN@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMHITCHECK(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMHITCHECK@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMHITCHECKSETINDEX(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMHITCHECKSETINDEX@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMINIT(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMINIT@16");
    if (f) f(a0, a1, a2, a3);
}
__declspec(dllexport) void __stdcall HMMSLEEP(int a0, int a1, int a2, int a3) {
    typedef void (__stdcall *F4)(int,int,int,int);
    F4 f = (F4)realfn("_HMMSLEEP@16");
    if (f) f(a0, a1, a2, a3);
}
